#!/usr/bin/env node
/* Build a single-file SPA at app/index.html by inlining src/styles.css and src/app.js
   into src/index.html. Run: `node build.js` */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const OUT = path.join(__dirname, 'app');

let html = fs.readFileSync(path.join(SRC, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(SRC, 'styles.css'), 'utf8');
let js = fs.readFileSync(path.join(SRC, 'app.js'), 'utf8');

// guard: a literal </script> in the JS would close the inlined block early
js = js.replace(/<\/script>/gi, '<\\/script>');

const linkTag = '<link rel="stylesheet" href="styles.css" />';
const scriptTag = '<script src="app.js"></script>';
if (!html.includes(linkTag) || !html.includes(scriptTag)) {
  console.error('build: expected <link>/<script> tags not found in src/index.html');
  process.exit(1);
}

html = html
  .replace(linkTag, `<style>\n${css}\n  </style>`)
  .replace(scriptTag, `<script>\n${js}\n  </script>`)
  .replace('<title>Flowscape — Water Logic</title>',
           '<title>Flowscape — Water Logic</title>\n  <!-- Single-file build — generated by build.js, do not edit. Edit src/ then run `node build.js`. -->');

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'index.html'), html);
console.log(`Built app/index.html (${html.length.toLocaleString()} bytes) from src/`);
